name: 'service_desk_analytics'
version: '1.0.0'
config-version: 2

profile: 'service_desk_analytics'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  service_desk_analytics:
    staging:
      +materialized: view
      +schema: "{{ env_var('BQ_DATASET_STAGING') }}"
    intermediate:
      +materialized: table
      +schema: "{{ env_var('BQ_DATASET_INTERMEDIATE') }}"
    marts:
      +materialized: table
      +schema: "{{ env_var('BQ_DATASET_MARTS') }}"
