version: '3.8'

services:
  gerar-dados:
    build: .
    container_name: gerar_chamados
    volumes:
      - ./python/data:/app/data
    command: python gerar_chamados.py

  upload-bq:
    build: .
    container_name: upload_chamados
    volumes:
      - ./python/data:/app/data
      - ./keys:/app/keys
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/credentials.json
    depends_on:
      - gerar-dados
    command: python upload_bigquery.py

  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.8.0
    container_name: dbt_transform
    volumes:
      - ./dbt:/usr/app/dbt
      - ./keys:/usr/app/keys
    working_dir: /usr/app/dbt
    env_file:
      - .env
    command: ["run", "--target", "prod"]